using System.Net;
using System.Net.Mail;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Datemulte_2.Services;

public class EmailService
{
    private readonly string _smtpHost;
    private readonly int _smtpPort;
    private readonly string _smtpUsername;
    private readonly string _smtpPassword;
    private readonly string _fromAddress;
    private readonly string _fromName;

    private readonly ILogger<EmailService> _logger;

    public EmailService(IConfiguration config, ILogger<EmailService> logger)
    {
        _logger = logger;
        _smtpHost = config["Email:Host"] ?? "";
        if (!int.TryParse(config["Email:Port"], out _smtpPort))
        {
            _smtpPort = 587; // Default fallback
        }
        _smtpUsername = config["Email:Username"] ?? "";
        _smtpPassword = config["Email:Password"] ?? "";
        _fromAddress = config["Email:FromAddress"] ?? "noreply@datemulte.com";
        _fromName = config["Email:FromName"] ?? "";
    }

    public async Task<(bool success, string? error)> SendEmailAsync(string toEmail, string subject, string htmlBody, string? plainTextBody = null)
    {
        try
        {
            // If email is not configured, simulate sending (Log it) and return success
            // This allows the app to function in dev environments without SMTP
            if(string.IsNullOrEmpty(_smtpHost) || string.IsNullOrEmpty(_smtpUsername))
            {
                _logger.LogWarning("Email not configured. Simulating email send to {ToEmail}", toEmail);
                _logger.LogInformation("Subject: {Subject}", subject);
                _logger.LogDebug("Body: {Body}", htmlBody);
                
                // Return true so the calling code proceeds as if successful
                return (true, null);
            }

            using var message = new MailMessage();
            message.From = new MailAddress(_fromAddress, _fromName);
            message.To.Add(new MailAddress(toEmail));
            message.Subject = subject;
            message.Body = htmlBody;
            message.IsBodyHtml = true;

            if (!string.IsNullOrEmpty(plainTextBody))
            {
                var plainView = AlternateView.CreateAlternateViewFromString(plainTextBody, null, "text/plain");
                message.AlternateViews.Add(plainView);
            }

            using var smtpClient = new SmtpClient(_smtpHost, _smtpPort);
            smtpClient.Credentials = new NetworkCredential(_smtpUsername, _smtpPassword);
            smtpClient.EnableSsl = true;

            await smtpClient.SendMailAsync(message);
            return (true, null);
        }
        catch(Exception ex)
        {
            _logger.LogError(ex, "Failed to send email to {ToEmail}", toEmail);
            return (false, ex.Message);
        }
    }

    public async Task<(bool success, string?error)> SendSessionSharedEmailAsync(string toEmail, string sharedByUsername, string sessionName, string sessionUrl)
    {
        var subject = $"{sharedByUsername} shared a session with you";
        var htmlBody = $@"
            <h2>Session Shared</h2>
            <p><strong>{sharedByUsername}</strong> has shared a data session with you:</p>
            <p><strong>Session:</strong> {sessionName}</p>
            <p><a href=""{sessionUrl}"" style=""background-color: #4CAF50; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;"">View Session</a></p>
            <p>Generated by DateMulte</p>
            ";

        return await SendEmailAsync(toEmail, subject, htmlBody);
    }

    public async Task<(bool success, string? error)> SendCommentNotificationEmailAsync(string toEmail, string commenterName, string sessionName, string commentText, string sessionUrl)
    {
        var subject = $"New comment on {sessionName}";
        var htmlBody = $@"
            <h2>New Comment</h2>
            <p><strong>{commenterName}</strong> commented on <strong>{sessionName}</strong>:</p>
            <blockquote style=""border-left: 3px solid #ccc; padding-left: 10px; margin: 10px 0;"">{commentText}</blockquote>
            <p><a href=""{sessionUrl}"" style=""background-color: #2196F3; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;"">View Session</a></p>
            <p>Generated by Datemulte</p>
        ";

        return await SendEmailAsync(toEmail, subject, htmlBody);
    }

    public async Task<(bool success, string? error)> SendInvitationEmailAsync(string email, string sessionName, string invitationUrl)
    {
        var subject = $"You've been invited to collaborate on {sessionName}";
        var htmlBody = $@"
            <h2>Session Invitation</h2>
            <p>You have been invited to access the session <strong>{sessionName}</strong>.</p>
            <p><a href='{invitationUrl}' style='background-color: #20818e; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;'>Click here to accept the invitation</a></p>
            <p>If you don't have an account, you'll be prompted to register.</p>
            <p>Generated by Datemulte</p>";
        
        return await SendEmailAsync(email, subject, htmlBody);
    }
}