export { createApp } from "./http"
export { FileStore } from "./storage"
export { addReference, detect, audioSamples } from "./detection"
export { AcousticDetector, DEFAULT_DETECTOR_SETTINGS } from "./lib/acoustic-detector"
export { ReferenceMatcher } from "./lib/acoustic-matching"
export { buildReferenceSet, extractRecordingReferences } from "./lib/acoustic-references"
export { analyzeRecordingSync } from "./lib/acoustic-recording-analysis"
export { calibrate } from "./lib/acoustic-calibration"
export { scoreRecording } from "./lib/acoustic-evaluation"
export { MATCH_SAMPLE_RATE, MATCH_FRAME_SIZE, MATCH_HOP_SIZE } from "./lib/acoustic-features"
